#include "datatypes.h"

const char* mc_interface_fault_to_string(int fault) {
	switch (fault) {
	case FAULT_CODE_NONE: return "NONE"; break;
	case FAULT_CODE_OVER_VOLTAGE: return "OVER_VOLTAGE"; break;
	case FAULT_CODE_UNDER_VOLTAGE: return "UNDER_VOLTAGE"; break;
	case FAULT_CODE_DRV: return "DRV"; break;
	case FAULT_CODE_ABS_OVER_CURRENT: return "ABS_OVER_CURRENT"; break;
	case FAULT_CODE_OVER_TEMP_FET: return "OVER_TEMP_FET"; break;
	case FAULT_CODE_OVER_TEMP_MOTOR: return "OVER_TEMP_MOTOR"; break;
	case FAULT_CODE_GATE_DRIVER_OVER_VOLTAGE: return "GATE_DRIVER_OVER_VOLTAGE"; break;
	case FAULT_CODE_GATE_DRIVER_UNDER_VOLTAGE: return "GATE_DRIVER_UNDER_VOLTAGE"; break;
	case FAULT_CODE_MCU_UNDER_VOLTAGE: return "MCU_UNDER_VOLTAGE"; break;
	case FAULT_CODE_BOOTING_FROM_WATCHDOG_RESET: return "BOOTING_FROM_WATCHDOG_RESET"; break;
	case FAULT_CODE_ENCODER_SPI: return "ENCODER_SPI"; break;
	case FAULT_CODE_ENCODER_SINCOS_BELOW_MIN_AMPLITUDE: return "ENCODER_SINCOS_BELOW_MIN_AMPLITUDE"; break;
	case FAULT_CODE_ENCODER_SINCOS_ABOVE_MAX_AMPLITUDE: return "ENCODER_SINCOS_ABOVE_MAX_AMPLITUDE"; break;
    case FAULT_CODE_FLASH_CORRUPTION: return "FLASH_CORRUPTION";
    case FAULT_CODE_FLASH_CORRUPTION_APP_CFG: return "FLASH_CORRUPTION_APP_CFG";
    case FAULT_CODE_FLASH_CORRUPTION_MC_CFG: return "FLASH_CORRUPTION_MC_CFG";
    case FAULT_CODE_HIGH_OFFSET_CURRENT_SENSOR_1: return "HIGH_OFFSET_CURRENT_SENSOR_1";
    case FAULT_CODE_HIGH_OFFSET_CURRENT_SENSOR_2: return "HIGH_OFFSET_CURRENT_SENSOR_2";
    case FAULT_CODE_HIGH_OFFSET_CURRENT_SENSOR_3: return "HIGH_OFFSET_CURRENT_SENSOR_3";
    case FAULT_CODE_UNBALANCED_CURRENTS: return "UNBALANCED_CURRENTS";
    case FAULT_CODE_BRK: return "CODE_BRK";
	default: return "FAULT_UNKNOWN"; break;
	}
}